### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by R1yuu** [eruption-project/eruption#184]
Hey, did u ever think about joining GitHub Sponsors?
Are you maybe already on the waiting list?, or is it not supported in your country yet?
Would love to support you and your work!

**Comment by X3n0m0rph59** [comment]
Hi @R1yuu, thanks for your suggestion!

Yes, I thought about applying for GitHub Sponsors... But nothing has been done yet. I still have to do some research about the legal implications of that.

It would certainly be cool to allow users to donate some money for a specific development task or for a specific device. This would definitely enable me to pick up new hardware, and add support for it more quickly.

**Comment by X3n0m0rph59** [comment]
@R1yuu The sponsorship links are now in place on GitHub.
Thanks again for suggesting this and for your donation as well! It is very much appreciated!
